name: Building and deploying ASP apps to Azure Web App - mouhib-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: 'https://mouhib-app.azurewebsites.net'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies using NuGet
      run: nuget restore WebApplication2.sln

    - name: Publish application with dotnet
      run: dotnet publish WebApplication2.csproj --configuration Release --output ./published

    - name: List files in the entire workspace (for debugging)
      run: dir 

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mouhib-app'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_898C1390A5E340D8AA87C6C20E341BAB }}
        package: "./published"
