name: Building and deploying ASP apps to Azure Web App - mouhib-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: 'https://mouhib-app.azurewebsites.net'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies using NuGet
      run: nuget restore WebApplication2.sln

    - name: Build application with msbuild
      run: msbuild WebApplication2.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:OutDir=./published/

    - name: List files in the entire workspace (for debugging)
      run: dir 

    - name: Display the content of the published directory
      run: dir ./published

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mouhib-app'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: "./published"

